version: '3.1'

volumes:
    zookeeper_data: {}
    zookeeper_datalog: {}
    kafka_data: {}

services:

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  kafka:    
    image: wurstmeister/kafka
    restart: always
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092
      KAFKA_LISTENERS: INSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "flights:1:1,fast-logs:1:1" #2 partitions, 1 replica 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 1073741824 #1GB
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/var/lib/kafka/data      
    depends_on:
      - zookeeper

  server:
    restart: always
    build: ./server
    container_name: server
    ports:
      - 8080:8080
    depends_on: 
      - kafka

  client:
    restart: always
    build: ./client
    container_name: client
    ports:
      - 8081:8081
    depends_on: 
      - server